[build]
  command = "cd portfolio-react && npm install && npm run build"
  publish = "portfolio-react/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200